/*
 * CIMB Securities API
 * API to describe how notifications should be sent to each account owner.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: soln.csit@cimb.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.local.model;


public class Book {
	
	private String author;
	private String series;
	private String name;


	public String getAuthor() {
		return author;
	}


	public void setAuthor(String author) {
		this.author = author;
	}


	public String getSeries() {
		return series;
	}


	public void setSeries(String series) {
		this.series = series;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}

}

